"""PN1 primorial sieve-rung relational inheritance test.

Registration: T227 in MASTER_PREDICTION_LEDGER.md
Frozen protocol: PN1_SIEVE_RUNG_PROTOCOL_v1_FROZEN.md
Protocol SHA256: EE14829EEA0D2BAAE05C37FAE2AA558F015EFC649FBFA54F0A563A7CE277DF9D
Data: exact reduced-residue wheels generated by this script; no external data.
Frozen: 2026-07-17 before any PN1 wheel results were generated or inspected.

The exact sieve checks are calibration.  The primary held-out claim compares
ordered parent relation distributions with order-destroying permutations for
the untouched 13->17 and 17->19 transitions.
"""

from __future__ import annotations

import hashlib
import json
import math
import platform
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd
from PIL import Image, ImageDraw, ImageFont


PRIMES = (2, 3, 5, 7, 11, 13, 17, 19)
HOLDOUT_TRANSITIONS = ((13, 17), (17, 19))
SEED = 20260717
N_SHUFFLES = 200
PAIR_BINS_PRIMARY = 64
TRIPLE_BINS_PRIMARY = 24
PAIR_BINS_SENSITIVITY = (32, 64, 128)
TRIPLE_BINS_SENSITIVITY = (12, 24, 36)
PROTOCOL_SHA256 = "EE14829EEA0D2BAAE05C37FAE2AA558F015EFC649FBFA54F0A563A7CE277DF9D"

HERE = Path(__file__).resolve().parent
PROTOCOL_PATH = HERE / "PN1_SIEVE_RUNG_PROTOCOL_v1_FROZEN.md"


@dataclass(frozen=True)
class Wheel:
    max_prime: int
    period: int
    residues: np.ndarray
    gaps: np.ndarray


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest().upper()


def generate_wheel(primes: tuple[int, ...]) -> Wheel:
    """Generate the exact reduced residue wheel modulo the primorial."""
    period = math.prod(primes)
    admissible = np.ones(period, dtype=bool)
    for prime in primes:
        admissible[::prime] = False
    residues = np.flatnonzero(admissible).astype(np.int64)
    wrapped = np.concatenate((residues, residues[:1] + period))
    gaps = np.diff(wrapped).astype(np.int32)
    if int(gaps.sum()) != period:
        raise AssertionError("Circular gaps do not close to the primorial period")
    expected_phi = math.prod(prime - 1 for prime in primes)
    if len(residues) != expected_phi:
        raise AssertionError("Reduced residue count does not match Euler totient")
    return Wheel(primes[-1], period, residues, gaps)


def pair_coordinate(gaps: np.ndarray) -> np.ndarray:
    left = gaps.astype(np.float64, copy=False)
    right = np.roll(left, -1)
    return 2.0 * right / (left + right)


def pair_histogram(gaps: np.ndarray, bins: int, mask: np.ndarray | None = None) -> np.ndarray:
    values = pair_coordinate(gaps)
    if mask is not None:
        values = values[mask]
    counts, _ = np.histogram(values, bins=np.linspace(0.0, 2.0, bins + 1))
    probabilities = counts.astype(np.float64)
    probabilities /= probabilities.sum()
    return probabilities


def triple_histogram(gaps: np.ndarray, bins: int, mask: np.ndarray | None = None) -> np.ndarray:
    first = pair_coordinate(gaps)
    second = np.roll(first, -1)
    if mask is not None:
        first = first[mask]
        second = second[mask]
    counts, _, _ = np.histogram2d(
        first,
        second,
        bins=(np.linspace(0.0, 2.0, bins + 1), np.linspace(0.0, 2.0, bins + 1)),
    )
    probabilities = counts.astype(np.float64).ravel()
    probabilities /= probabilities.sum()
    return probabilities


def js_divergence_bits(p: np.ndarray, q: np.ndarray) -> float:
    """Jensen-Shannon divergence in bits, bounded from zero to one."""
    p = np.asarray(p, dtype=np.float64)
    q = np.asarray(q, dtype=np.float64)
    p = p / p.sum()
    q = q / q.sum()
    midpoint = 0.5 * (p + q)

    def kl_term(a: np.ndarray, b: np.ndarray) -> float:
        active = a > 0
        return float(np.sum(a[active] * np.log2(a[active] / b[active])))

    return 0.5 * kl_term(p, midpoint) + 0.5 * kl_term(q, midpoint)


def semicircle_mask_from_residues(residues: np.ndarray, period: int, half: int) -> np.ndarray:
    if half == 0:
        return residues < period / 2
    return residues >= period / 2


def shuffled_residue_positions(gaps: np.ndarray, first_residue: int, period: int) -> np.ndarray:
    positions = first_residue + np.concatenate(([0], np.cumsum(gaps[:-1], dtype=np.int64)))
    return np.mod(positions, period)


def calibration_check(parent: Wheel, child: Wheel, next_prime: int) -> dict[str, object]:
    lifts = parent.residues[:, None] + parent.period * np.arange(next_prime, dtype=np.int64)[None, :]
    release_matrix = np.mod(lifts, next_prime) == 0
    lifted_flat = lifts.ravel()
    release_flat = release_matrix.ravel()
    survivors = np.sort(lifted_flat[~release_flat])
    shed = np.sort(lifted_flat[release_flat])
    reconstructed = np.sort(np.concatenate((survivors, shed)))

    release_count_exact = int(release_flat.sum()) == len(parent.residues)
    release_fraction = float(release_flat.mean())
    expected_release_fraction = 1.0 / next_prime
    disjoint = np.intersect1d(survivors, shed, assume_unique=True).size == 0
    reconstructs_lift = np.array_equal(reconstructed, np.sort(lifted_flat))
    survivors_match_child = np.array_equal(survivors, child.residues)
    phase_exact = bool(np.array_equal(release_flat, np.mod(lifted_flat, next_prime) == 0))

    # Each parent-local geometry context is repeated q times. Because gcd(P_k,q)=1,
    # the q lifts visit every modular phase once, so every context has one release.
    row_release_counts = release_matrix.sum(axis=1)
    geometry_context_exactly_one_release = bool(np.all(row_release_counts == 1))
    geometry_conditional_max_error = float(
        np.max(np.abs(row_release_counts / next_prime - expected_release_fraction))
    )
    geometry_mutual_information_bits = 0.0 if geometry_conditional_max_error == 0.0 else float("nan")

    return {
        "transition": f"{parent.max_prime}->{next_prime}",
        "parent_period": parent.period,
        "child_period": child.period,
        "parent_slots": len(parent.residues),
        "lifted_slots": len(lifted_flat),
        "survivor_slots": len(survivors),
        "shed_slots": len(shed),
        "release_fraction_measured": release_fraction,
        "release_fraction_exact": expected_release_fraction,
        "release_count_exact": release_count_exact,
        "survivor_shed_disjoint": bool(disjoint),
        "reconstructs_lifted_parent": bool(reconstructs_lift),
        "survivors_match_child": bool(survivors_match_child),
        "phase_rule_exact": phase_exact,
        "geometry_context_exactly_one_release": geometry_context_exactly_one_release,
        "geometry_conditional_max_error": geometry_conditional_max_error,
        "geometry_mutual_information_bits": geometry_mutual_information_bits,
        "all_exact_checks_pass": bool(
            release_count_exact
            and disjoint
            and reconstructs_lift
            and survivors_match_child
            and phase_exact
            and geometry_context_exactly_one_release
            and geometry_conditional_max_error == 0.0
        ),
    }


def run_transition(
    parent: Wheel,
    child: Wheel,
    next_prime: int,
    seed: int,
) -> tuple[list[dict[str, object]], list[dict[str, object]], list[dict[str, object]], dict[str, np.ndarray]]:
    rng = np.random.default_rng(seed)

    pair_child = {
        bins: pair_histogram(child.gaps, bins) for bins in PAIR_BINS_SENSITIVITY
    }
    triple_child = {
        bins: triple_histogram(child.gaps, bins) for bins in TRIPLE_BINS_SENSITIVITY
    }
    pair_parent = {
        bins: pair_histogram(parent.gaps, bins) for bins in PAIR_BINS_SENSITIVITY
    }
    triple_parent = {
        bins: triple_histogram(parent.gaps, bins) for bins in TRIPLE_BINS_SENSITIVITY
    }

    pair_ordered = {
        bins: js_divergence_bits(pair_parent[bins], pair_child[bins])
        for bins in PAIR_BINS_SENSITIVITY
    }
    triple_ordered = {
        bins: js_divergence_bits(triple_parent[bins], triple_child[bins])
        for bins in TRIPLE_BINS_SENSITIVITY
    }

    pair_shuffle_distances = {
        bins: np.empty(N_SHUFFLES, dtype=np.float64) for bins in PAIR_BINS_SENSITIVITY
    }
    triple_shuffle_distances = {
        bins: np.empty(N_SHUFFLES, dtype=np.float64) for bins in TRIPLE_BINS_SENSITIVITY
    }
    pair_shuffle_hist_sum = np.zeros_like(pair_parent[PAIR_BINS_PRIMARY])

    split_results: dict[tuple[str, int], dict[str, object]] = {}
    for half in (0, 1):
        parent_mask = semicircle_mask_from_residues(parent.residues, parent.period, half)
        child_mask = semicircle_mask_from_residues(child.residues, child.period, half)
        split_results[("pair", half)] = {
            "ordered": js_divergence_bits(
                pair_histogram(parent.gaps, PAIR_BINS_PRIMARY, parent_mask),
                pair_histogram(child.gaps, PAIR_BINS_PRIMARY, child_mask),
            ),
            "shuffle": np.empty(N_SHUFFLES, dtype=np.float64),
        }
        split_results[("triple", half)] = {
            "ordered": js_divergence_bits(
                triple_histogram(parent.gaps, TRIPLE_BINS_PRIMARY, parent_mask),
                triple_histogram(child.gaps, TRIPLE_BINS_PRIMARY, child_mask),
            ),
            "shuffle": np.empty(N_SHUFFLES, dtype=np.float64),
        }

    child_half_pair = {
        half: pair_histogram(
            child.gaps,
            PAIR_BINS_PRIMARY,
            semicircle_mask_from_residues(child.residues, child.period, half),
        )
        for half in (0, 1)
    }
    child_half_triple = {
        half: triple_histogram(
            child.gaps,
            TRIPLE_BINS_PRIMARY,
            semicircle_mask_from_residues(child.residues, child.period, half),
        )
        for half in (0, 1)
    }

    for shuffle_index in range(N_SHUFFLES):
        shuffled = rng.permutation(parent.gaps)
        for bins in PAIR_BINS_SENSITIVITY:
            histogram = pair_histogram(shuffled, bins)
            pair_shuffle_distances[bins][shuffle_index] = js_divergence_bits(
                histogram, pair_child[bins]
            )
            if bins == PAIR_BINS_PRIMARY:
                pair_shuffle_hist_sum += histogram
        for bins in TRIPLE_BINS_SENSITIVITY:
            histogram = triple_histogram(shuffled, bins)
            triple_shuffle_distances[bins][shuffle_index] = js_divergence_bits(
                histogram, triple_child[bins]
            )

        shuffled_positions = shuffled_residue_positions(
            shuffled, int(parent.residues[0]), parent.period
        )
        for half in (0, 1):
            shuffled_mask = semicircle_mask_from_residues(
                shuffled_positions, parent.period, half
            )
            split_results[("pair", half)]["shuffle"][shuffle_index] = js_divergence_bits(
                pair_histogram(shuffled, PAIR_BINS_PRIMARY, shuffled_mask),
                child_half_pair[half],
            )
            split_results[("triple", half)]["shuffle"][shuffle_index] = js_divergence_bits(
                triple_histogram(shuffled, TRIPLE_BINS_PRIMARY, shuffled_mask),
                child_half_triple[half],
            )

    primary_rows: list[dict[str, object]] = []
    sensitivity_rows: list[dict[str, object]] = []

    def summarize(
        observable: str,
        bins: int,
        ordered: float,
        shuffled_distances: np.ndarray,
        primary: bool,
    ) -> dict[str, object]:
        p_value = (1 + int(np.sum(shuffled_distances <= ordered))) / (N_SHUFFLES + 1)
        row = {
            "transition": f"{parent.max_prime}->{next_prime}",
            "observable": observable,
            "bins": bins,
            "parent_slots": len(parent.gaps),
            "child_slots": len(child.gaps),
            "ordered_jsd_bits": ordered,
            "shuffle_median_jsd_bits": float(np.median(shuffled_distances)),
            "shuffle_q05_jsd_bits": float(np.quantile(shuffled_distances, 0.05)),
            "shuffle_q95_jsd_bits": float(np.quantile(shuffled_distances, 0.95)),
            "permutation_p_one_sided": p_value,
            "ordered_beats_shuffle_median": bool(ordered < np.median(shuffled_distances)),
            "passes_frozen_primary": bool(
                ordered < np.median(shuffled_distances) and p_value <= 0.05
            ) if primary else None,
        }
        return row

    for bins in PAIR_BINS_SENSITIVITY:
        row = summarize(
            "pair_x",
            bins,
            pair_ordered[bins],
            pair_shuffle_distances[bins],
            bins == PAIR_BINS_PRIMARY,
        )
        (primary_rows if bins == PAIR_BINS_PRIMARY else sensitivity_rows).append(row)
    for bins in TRIPLE_BINS_SENSITIVITY:
        row = summarize(
            "triple_xx",
            bins,
            triple_ordered[bins],
            triple_shuffle_distances[bins],
            bins == TRIPLE_BINS_PRIMARY,
        )
        (primary_rows if bins == TRIPLE_BINS_PRIMARY else sensitivity_rows).append(row)

    split_rows: list[dict[str, object]] = []
    for (observable, half), values in split_results.items():
        shuffled_distances = values["shuffle"]
        ordered = float(values["ordered"])
        p_value = (1 + int(np.sum(shuffled_distances <= ordered))) / (N_SHUFFLES + 1)
        split_rows.append(
            {
                "transition": f"{parent.max_prime}->{next_prime}",
                "observable": observable,
                "half": half + 1,
                "ordered_jsd_bits": ordered,
                "shuffle_median_jsd_bits": float(np.median(shuffled_distances)),
                "permutation_p_one_sided": p_value,
                "passes_same_direction": bool(
                    ordered < np.median(shuffled_distances) and p_value <= 0.05
                ),
            }
        )

    # Coordinate-rival audit. Transforming the registered x-bin edges into
    # log-ratio edges must produce the same counts because the map is monotone.
    x_edges = np.linspace(0.0, 2.0, PAIR_BINS_PRIMARY + 1)
    log_edges = np.empty_like(x_edges)
    log_edges[0] = -np.inf
    log_edges[-1] = np.inf
    interior = x_edges[1:-1]
    log_edges[1:-1] = np.log(interior / (2.0 - interior))

    def log_ratio_hist(gaps: np.ndarray) -> np.ndarray:
        values = np.log(np.roll(gaps.astype(np.float64), -1) / gaps)
        counts, _ = np.histogram(values, bins=log_edges)
        result = counts.astype(np.float64)
        return result / result.sum()

    log_parent = log_ratio_hist(parent.gaps)
    log_child = log_ratio_hist(child.gaps)
    coordinate_rival_jsd = js_divergence_bits(log_parent, log_child)
    coordinate_rival_abs_difference = abs(
        coordinate_rival_jsd - pair_ordered[PAIR_BINS_PRIMARY]
    )

    arrays = {
        f"{parent.max_prime}_{next_prime}_pair_parent": pair_parent[PAIR_BINS_PRIMARY],
        f"{parent.max_prime}_{next_prime}_pair_child": pair_child[PAIR_BINS_PRIMARY],
        f"{parent.max_prime}_{next_prime}_pair_shuffle_mean": pair_shuffle_hist_sum / N_SHUFFLES,
        f"{parent.max_prime}_{next_prime}_pair_shuffle_distances": pair_shuffle_distances[PAIR_BINS_PRIMARY],
        f"{parent.max_prime}_{next_prime}_triple_parent": triple_parent[TRIPLE_BINS_PRIMARY],
        f"{parent.max_prime}_{next_prime}_triple_child": triple_child[TRIPLE_BINS_PRIMARY],
        f"{parent.max_prime}_{next_prime}_triple_shuffle_distances": triple_shuffle_distances[TRIPLE_BINS_PRIMARY],
    }
    for row in primary_rows:
        row["coordinate_rival_log_ratio_jsd_bits"] = (
            coordinate_rival_jsd if row["observable"] == "pair_x" else None
        )
        row["coordinate_rival_abs_difference"] = (
            coordinate_rival_abs_difference if row["observable"] == "pair_x" else None
        )

    return primary_rows, sensitivity_rows, split_rows, arrays


def make_figure(
    primary: pd.DataFrame,
    arrays: dict[str, np.ndarray],
    output_path: Path,
) -> None:
    width, height = 1800, 760
    image = Image.new("RGB", (width, height), "#ffffff")
    draw = ImageDraw.Draw(image)

    def font(size: int, bold: bool = False) -> ImageFont.ImageFont:
        candidates = (
            [Path("C:/Windows/Fonts/arialbd.ttf"), Path("C:/Windows/Fonts/arial.ttf")]
            if bold
            else [Path("C:/Windows/Fonts/arial.ttf"), Path("C:/Windows/Fonts/calibri.ttf")]
        )
        for candidate in candidates:
            if candidate.exists():
                return ImageFont.truetype(str(candidate), size=size)
        return ImageFont.load_default()

    title_font = font(34, bold=True)
    panel_font = font(23, bold=True)
    label_font = font(18)
    small_font = font(15)
    tiny_font = font(13)
    ink = "#222831"
    muted = "#5d6570"
    grid = "#d9dde3"
    blue = "#2f6f9f"
    blue_edge = "#244c6a"
    gold = "#e7b65a"
    gold_edge = "#8f6725"

    draw.text((60, 28), "PN1 primorial sieve-rung test", fill=ink, font=title_font)
    draw.text(
        (60, 72),
        "Exact arithmetic wheels; held-out transitions 13→17 and 17→19; 200 fixed-seed order shuffles",
        fill=muted,
        font=label_font,
    )

    left_panel = (60, 130, 865, 700)
    right_panel = (935, 130, 1740, 700)
    for panel in (left_panel, right_panel):
        draw.rounded_rectangle(panel, radius=10, outline="#c8cdd4", width=2, fill="#fbfcfd")

    # Panel A: ordered versus shuffled JSD.
    draw.text((90, 156), "Held-out parent-to-child relation distance", fill=ink, font=panel_font)
    plot = (145, 220, 825, 590)
    values = np.r_[primary["ordered_jsd_bits"].to_numpy(), primary["shuffle_median_jsd_bits"].to_numpy()]
    ymax = max(float(values.max()) * 1.18, 1e-6)
    for tick in range(6):
        value = ymax * tick / 5
        y = int(plot[3] - (value / ymax) * (plot[3] - plot[1]))
        draw.line((plot[0], y, plot[2], y), fill=grid, width=1)
        label = f"{value:.3f}"
        draw.text((plot[0] - 58, y - 8), label, fill=muted, font=tiny_font)
    draw.line((plot[0], plot[1], plot[0], plot[3]), fill=ink, width=2)
    draw.line((plot[0], plot[3], plot[2], plot[3]), fill=ink, width=2)

    categories = list(primary.itertuples(index=False))
    group_width = (plot[2] - plot[0]) / len(categories)
    bar_width = 42
    for index, row in enumerate(categories):
        center = plot[0] + group_width * (index + 0.5)
        ordered_height = row.ordered_jsd_bits / ymax * (plot[3] - plot[1])
        shuffled_height = row.shuffle_median_jsd_bits / ymax * (plot[3] - plot[1])
        draw.rectangle(
            (center - bar_width - 4, plot[3] - ordered_height, center - 4, plot[3]),
            fill=blue,
            outline=blue_edge,
            width=2,
        )
        draw.rectangle(
            (center + 4, plot[3] - shuffled_height, center + bar_width + 4, plot[3]),
            fill=gold,
            outline=gold_edge,
            width=2,
        )
        relation = "pair" if row.observable == "pair_x" else "three-gap"
        first = str(row.transition)
        second = relation
        draw.text((center - draw.textlength(first, font=small_font) / 2, plot[3] + 14), first, fill=ink, font=small_font)
        draw.text((center - draw.textlength(second, font=tiny_font) / 2, plot[3] + 36), second, fill=muted, font=tiny_font)
    draw.text((160, 642), "ordered parent", fill=blue_edge, font=small_font)
    draw.rectangle((140, 644, 153, 657), fill=blue, outline=blue_edge)
    draw.text((355, 642), "median shuffled parent", fill=gold_edge, font=small_font)
    draw.rectangle((335, 644, 348, 657), fill=gold, outline=gold_edge)
    draw.text((90, 615), "Jensen–Shannon divergence (bits; lower is closer)", fill=muted, font=small_font)

    # Panel B: pair-coordinate distribution for the second transition.
    draw.text((965, 156), "Pair-coordinate distribution at 17→19", fill=ink, font=panel_font)
    plot = (1010, 220, 1700, 590)
    transition_key = "17_19"
    parent_hist = arrays[f"{transition_key}_pair_parent"]
    child_hist = arrays[f"{transition_key}_pair_child"]
    shuffle_hist = arrays[f"{transition_key}_pair_shuffle_mean"]
    ymax = max(float(parent_hist.max()), float(child_hist.max()), float(shuffle_hist.max())) * 1.12
    for tick in range(6):
        value = ymax * tick / 5
        y = int(plot[3] - (value / ymax) * (plot[3] - plot[1]))
        draw.line((plot[0], y, plot[2], y), fill=grid, width=1)
        draw.text((plot[0] - 56, y - 8), f"{value:.3f}", fill=muted, font=tiny_font)
    draw.line((plot[0], plot[1], plot[0], plot[3]), fill=ink, width=2)
    draw.line((plot[0], plot[3], plot[2], plot[3]), fill=ink, width=2)
    for tick in range(5):
        value = 0.5 * tick
        x = int(plot[0] + value / 2.0 * (plot[2] - plot[0]))
        draw.text((x - 10, plot[3] + 12), f"{value:.1f}", fill=muted, font=tiny_font)
    ridge_x = int(plot[0] + 0.5 * (plot[2] - plot[0]))
    for y in range(plot[1], plot[3], 10):
        draw.line((ridge_x, y, ridge_x, min(y + 4, plot[3])), fill="#6d737c", width=1)

    def points(series: np.ndarray) -> list[tuple[int, int]]:
        return [
            (
                int(plot[0] + index / (len(series) - 1) * (plot[2] - plot[0])),
                int(plot[3] - value / ymax * (plot[3] - plot[1])),
            )
            for index, value in enumerate(series)
        ]

    draw.line(points(child_hist), fill=ink, width=4)
    draw.line(points(parent_hist), fill=blue, width=3)
    shuffle_points = points(shuffle_hist)
    for index in range(0, len(shuffle_points) - 1, 4):
        draw.line(shuffle_points[index : min(index + 3, len(shuffle_points))], fill=gold_edge, width=3)
    draw.text((1080, 625), "child 19", fill=ink, font=small_font)
    draw.line((1050, 635, 1072, 635), fill=ink, width=4)
    draw.text((1230, 625), "ordered parent 17", fill=blue_edge, font=small_font)
    draw.line((1200, 635, 1222, 635), fill=blue, width=3)
    draw.text((1475, 625), "mean shuffled parent", fill=gold_edge, font=small_font)
    for x in range(1440, 1468, 8):
        draw.line((x, 635, x + 4, 635), fill=gold_edge, width=3)
    draw.text((1210, 672), "local ARA composition coordinate x", fill=muted, font=label_font)
    image.save(output_path, format="PNG")


def run_analysis(output_dir: Path | None = None) -> dict[str, object]:
    output_dir = Path(output_dir) if output_dir is not None else HERE
    output_dir.mkdir(parents=True, exist_ok=True)

    observed_protocol_hash = sha256_file(PROTOCOL_PATH)
    if observed_protocol_hash != PROTOCOL_SHA256:
        raise RuntimeError(
            f"Frozen protocol hash mismatch: {observed_protocol_hash} != {PROTOCOL_SHA256}"
        )

    wheels: dict[int, Wheel] = {}
    active_primes: list[int] = []
    for prime in PRIMES:
        active_primes.append(prime)
        wheels[prime] = generate_wheel(tuple(active_primes))

    wheel_rows = [
        {
            "max_prime": prime,
            "period": wheel.period,
            "slots": len(wheel.residues),
            "mean_gap": float(np.mean(wheel.gaps)),
            "max_gap": int(np.max(wheel.gaps)),
            "gap_sum": int(np.sum(wheel.gaps)),
        }
        for prime, wheel in wheels.items()
    ]

    calibration_rows: list[dict[str, object]] = []
    primary_rows: list[dict[str, object]] = []
    sensitivity_rows: list[dict[str, object]] = []
    split_rows: list[dict[str, object]] = []
    saved_arrays: dict[str, np.ndarray] = {}

    for transition_index, (parent_prime, child_prime) in enumerate(HOLDOUT_TRANSITIONS):
        parent = wheels[parent_prime]
        child = wheels[child_prime]
        calibration_rows.append(calibration_check(parent, child, child_prime))
        primary, sensitivity, splits, arrays = run_transition(
            parent,
            child,
            child_prime,
            seed=SEED + transition_index * 10000,
        )
        primary_rows.extend(primary)
        sensitivity_rows.extend(sensitivity)
        split_rows.extend(splits)
        saved_arrays.update(arrays)

    wheel_df = pd.DataFrame(wheel_rows)
    calibration_df = pd.DataFrame(calibration_rows)
    primary_df = pd.DataFrame(primary_rows)
    sensitivity_df = pd.DataFrame(sensitivity_rows)
    split_df = pd.DataFrame(split_rows)

    all_exact_checks_pass = bool(calibration_df["all_exact_checks_pass"].all())
    primary_pass_count = int(primary_df["passes_frozen_primary"].sum())
    primary_claim_pass = bool(primary_pass_count == len(primary_df) == 4)
    split_same_direction_count = int(split_df["passes_same_direction"].sum())
    coordinate_rival_max_abs_difference = float(
        primary_df["coordinate_rival_abs_difference"].dropna().max()
    )

    if not all_exact_checks_pass:
        rating = "INVALID IMPLEMENTATION"
    elif primary_claim_pass and split_same_direction_count == len(split_df):
        rating = "SUPPORTED [pre-registered, arithmetic, unreplicated]"
    else:
        rating = "NOT SUPPORTED"

    generated_at = datetime.now(timezone.utc).isoformat()
    results: dict[str, object] = {
        "test_id": "T227 / PN1/v1",
        "generated_at_utc": generated_at,
        "orientation": "up = larger primorial period / later sieve rung",
        "protocol_path": str(PROTOCOL_PATH.relative_to(HERE.parents[1])).replace("\\", "/"),
        "protocol_sha256_expected": PROTOCOL_SHA256,
        "protocol_sha256_observed": observed_protocol_hash,
        "seed": SEED,
        "n_shuffles": N_SHUFFLES,
        "holdout_transitions": [f"{a}->{b}" for a, b in HOLDOUT_TRANSITIONS],
        "wheel_inventory": wheel_rows,
        "calibration": calibration_rows,
        "primary": primary_rows,
        "sensitivity": sensitivity_rows,
        "split_half": split_rows,
        "summary": {
            "all_exact_checks_pass": all_exact_checks_pass,
            "primary_comparisons_passed": primary_pass_count,
            "primary_comparisons_total": len(primary_df),
            "primary_claim_pass": primary_claim_pass,
            "split_half_checks_passed": split_same_direction_count,
            "split_half_checks_total": len(split_df),
            "coordinate_rival_max_abs_jsd_difference": coordinate_rival_max_abs_difference,
            "rating": rating,
            "evidence_ceiling": (
                "Finite deterministic arithmetic relation; exact checks are reconstruction. "
                "No Riemann-Hypothesis or physical-universality inference."
            ),
        },
        "environment": {
            "python": sys.version,
            "platform": platform.platform(),
            "numpy": np.__version__,
            "pandas": pd.__version__,
        },
    }

    wheel_df.to_csv(output_dir / "PN1_WHEEL_INVENTORY.csv", index=False)
    calibration_df.to_csv(output_dir / "PN1_CALIBRATION_CHECKS.csv", index=False)
    primary_df.to_csv(output_dir / "PN1_PRIMARY_DISTANCES.csv", index=False)
    sensitivity_df.to_csv(output_dir / "PN1_BIN_SENSITIVITY.csv", index=False)
    split_df.to_csv(output_dir / "PN1_SPLIT_HALF_CHECKS.csv", index=False)
    np.savez_compressed(output_dir / "PN1_HISTOGRAMS_AND_NULLS.npz", **saved_arrays)
    with (output_dir / "PN1_SIEVE_RUNG_RESULTS.json").open("w", encoding="utf-8") as handle:
        json.dump(results, handle, indent=2, allow_nan=False)

    make_figure(primary_df, saved_arrays, output_dir / "PN1_SIEVE_RUNG_FIGURE.png")

    print("PN1 provenance")
    print(f"  protocol_sha256: {observed_protocol_hash}")
    print(f"  seed: {SEED}")
    print(f"  shuffles: {N_SHUFFLES}")
    print(f"  exact checks: {all_exact_checks_pass}")
    print(f"  primary: {primary_pass_count}/{len(primary_df)}")
    print(f"  split halves: {split_same_direction_count}/{len(split_df)}")
    print(f"  rating: {rating}")
    print(primary_df.to_string(index=False))
    return results


if __name__ == "__main__":
    run_analysis()
