"""
ara_phase_trust_gate_diagnostic.py

Strict-causal diagnostic for the next hybrid question:

    lag ridge = carried energy / native-unit inertia
    ARA phase-flow = route / timing / turn geometry

The goal is not to average lag and ARA.  The goal is to ask:

  1. When lag and ARA phase-flow disagree, which channel is more often right
     about direction/turn?
  2. Can ARA disagreement act as a warning that lag is entering a risky
     boundary/turn window?
  3. Does a simple causal trust selector help, using only past completed
     outcomes?

Leakage guard:

  - Base lag and phase-flow predictions are generated by the strict-causal
    functions from ara_lag_phase_hybrid_predictor.py.
  - At origin t, training pairs for base models obey s+h<t.
  - The trust selector for origin t only uses previous records whose
    target_anchor < t, so their outcomes would already be known.
"""

from __future__ import annotations

import json
import math
import sys
import time
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(REPO_ROOT))

from ara_geometry_analog_flow_predictor import compact_state_features
from ara_geometry_transport_test import (
    BASE,
    HOME_PERIOD,
    HORIZONS,
    RUNG_KS,
    START_YEAR,
    build_snapshot,
    clean_for_json,
    load_enso_frame,
    score_points,
    zscore_columns,
)
from ara_lag_phase_hybrid_predictor import (
    MIN_FLOW_TRAIN,
    ORIGIN_STRIDE,
    enso_class,
    extended_score,
    finite,
    format_score,
    point,
    predict_components_for_origin,
)
from ara_phase_flow_predictor import PHASE_KEYS, phase_clean_input, phase_velocity_input


OUT_JSON = HERE / "ara_phase_trust_gate_diagnostic_result.json"
OUT_JS = HERE / "ara_phase_trust_gate_diagnostic_result.js"

MIN_META_BUCKET = 18
MIN_META_FALLBACK = 35
EPS = 1e-9


def sgn(value):
    value = finite(value)
    if value > EPS:
        return 1
    if value < -EPS:
        return -1
    return 0


def rounded(value, digits=6):
    if value is None:
        return None
    value = finite(value)
    return round(value, digits)


def is_transition(record):
    return enso_class(record["actual"]) != enso_class(record["persistence"])


def actual_direction(record):
    return sgn(record["actual"] - record["persistence"])


def lag_direction(record):
    return sgn(record["lag_pred"] - record["persistence"])


def phase_direction(record):
    return sgn(record["phase_pred"] - record["persistence"])


def lag_correct(record):
    return lag_direction(record) == actual_direction(record)


def phase_correct(record):
    return phase_direction(record) == actual_direction(record)


def lag_error(record):
    return abs(record["lag_pred"] - record["actual"])


def phase_error(record):
    return abs(record["phase_pred"] - record["actual"])


def lag_phase_disagree(record):
    return lag_direction(record) != phase_direction(record)


def lag_phase_agree(record):
    return lag_direction(record) == phase_direction(record)


def boundary_cross_prediction(pred, persistence):
    return enso_class(pred) != enso_class(persistence)


def trust_bucket(record):
    """Small, interpretable buckets known at forecast time."""
    if lag_phase_agree(record):
        return "agree_same_direction"

    lag_cross = boundary_cross_prediction(record["lag_pred"], record["persistence"])
    phase_cross = boundary_cross_prediction(record["phase_pred"], record["persistence"])
    phase_stronger = abs(record["phase_pred"] - record["persistence"]) > abs(record["lag_pred"] - record["persistence"])

    if lag_cross and not phase_cross:
        return "disagree_lag_cross_only"
    if phase_cross and not lag_cross:
        return "disagree_phase_cross_only"
    if lag_cross and phase_cross:
        return "disagree_both_cross"
    if phase_stronger:
        return "disagree_phase_stronger"
    return "disagree_lag_stronger"


def coarse_bucket(record):
    return "disagree" if lag_phase_disagree(record) else "agree"


def choose_by_history(record, available, metric):
    """Choose lag or phase from past completed outcomes in the same condition."""
    bucket = trust_bucket(record)
    bucket_records = [r for r in available if trust_bucket(r) == bucket]
    if len(bucket_records) < MIN_META_BUCKET:
        bucket_records = [r for r in available if coarse_bucket(r) == coarse_bucket(record)]
    if len(bucket_records) < MIN_META_FALLBACK:
        return "lag", {
            "bucket": bucket,
            "used_bucket": "fallback_lag",
            "past_n": len(bucket_records),
            "lag_dir_acc": None,
            "phase_dir_acc": None,
            "lag_mae": None,
            "phase_mae": None,
        }

    lag_dir_acc = float(np.mean([lag_correct(r) for r in bucket_records]))
    phase_dir_acc = float(np.mean([phase_correct(r) for r in bucket_records]))
    lag_mae = float(np.mean([lag_error(r) for r in bucket_records]))
    phase_mae = float(np.mean([phase_error(r) for r in bucket_records]))

    if metric == "direction":
        choice = "phase" if phase_dir_acc > lag_dir_acc and phase_mae <= lag_mae * 1.15 else "lag"
    elif metric == "mae":
        choice = "phase" if phase_mae < lag_mae else "lag"
    else:
        raise ValueError(f"unknown selector metric: {metric}")

    return choice, {
        "bucket": bucket,
        "used_bucket": bucket if len([r for r in available if trust_bucket(r) == bucket]) >= MIN_META_BUCKET else coarse_bucket(record),
        "past_n": len(bucket_records),
        "lag_dir_acc": lag_dir_acc,
        "phase_dir_acc": phase_dir_acc,
        "lag_mae": lag_mae,
        "phase_mae": phase_mae,
    }


def subset_summary(records):
    if not records:
        return {
            "n": 0,
            "lag_turn_accuracy": None,
            "phase_turn_accuracy": None,
            "lag_mae": None,
            "phase_mae": None,
            "lag_closer_rate": None,
            "phase_closer_rate": None,
            "both_correct_rate": None,
            "lag_only_correct_rate": None,
            "phase_only_correct_rate": None,
            "neither_correct_rate": None,
            "lag_boundary_cross_accuracy": None,
            "phase_boundary_cross_accuracy": None,
            "actual_transition_rate": None,
        }

    lag_ok = np.asarray([lag_correct(r) for r in records], dtype=bool)
    phase_ok = np.asarray([phase_correct(r) for r in records], dtype=bool)
    lag_err = np.asarray([lag_error(r) for r in records], dtype=float)
    phase_err = np.asarray([phase_error(r) for r in records], dtype=float)
    lag_cross = np.asarray([boundary_cross_prediction(r["lag_pred"], r["persistence"]) for r in records], dtype=bool)
    phase_cross = np.asarray([boundary_cross_prediction(r["phase_pred"], r["persistence"]) for r in records], dtype=bool)
    actual_cross = np.asarray([is_transition(r) for r in records], dtype=bool)

    return {
        "n": int(len(records)),
        "lag_turn_accuracy": float(np.mean(lag_ok)),
        "phase_turn_accuracy": float(np.mean(phase_ok)),
        "lag_mae": float(np.mean(lag_err)),
        "phase_mae": float(np.mean(phase_err)),
        "lag_closer_rate": float(np.mean(lag_err < phase_err)),
        "phase_closer_rate": float(np.mean(phase_err < lag_err)),
        "both_correct_rate": float(np.mean(lag_ok & phase_ok)),
        "lag_only_correct_rate": float(np.mean(lag_ok & ~phase_ok)),
        "phase_only_correct_rate": float(np.mean(~lag_ok & phase_ok)),
        "neither_correct_rate": float(np.mean(~lag_ok & ~phase_ok)),
        "lag_boundary_cross_accuracy": float(np.mean(lag_cross == actual_cross)),
        "phase_boundary_cross_accuracy": float(np.mean(phase_cross == actual_cross)),
        "actual_transition_rate": float(np.mean(actual_cross)),
    }


def warning_summary(records):
    if not records:
        return {"n": 0}
    warnings = np.asarray([lag_phase_disagree(r) for r in records], dtype=bool)
    lag_wrong = np.asarray([not lag_correct(r) for r in records], dtype=bool)
    transitions = np.asarray([is_transition(r) for r in records], dtype=bool)
    out = {
        "n": int(len(records)),
        "warning_rate": float(np.mean(warnings)),
        "lag_wrong_rate": float(np.mean(lag_wrong)),
        "transition_rate": float(np.mean(transitions)),
        "lag_wrong_given_warning": float(np.mean(lag_wrong[warnings])) if np.any(warnings) else None,
        "lag_wrong_given_no_warning": float(np.mean(lag_wrong[~warnings])) if np.any(~warnings) else None,
        "transition_given_warning": float(np.mean(transitions[warnings])) if np.any(warnings) else None,
        "transition_given_no_warning": float(np.mean(transitions[~warnings])) if np.any(~warnings) else None,
        "warning_recall_for_lag_wrong": float(np.mean(warnings[lag_wrong])) if np.any(lag_wrong) else None,
        "warning_recall_for_transition": float(np.mean(warnings[transitions])) if np.any(transitions) else None,
    }
    return out


def points_from_records(records, model_key):
    pts = []
    for r in records:
        pred = r[model_key]
        pts.append(point(r["origin_date"], r["target_date"], pred, r["actual"], r["persistence"]))
    return pts


def add_selector_predictions(records, metric):
    key = f"selector_{metric}_pred"
    choice_key = f"selector_{metric}_choice"
    meta_key = f"selector_{metric}_meta"
    for record in records:
        available = [r for r in records if r["target_anchor"] < record["origin_anchor"]]
        choice, meta = choose_by_history(record, available, metric)
        record[choice_key] = choice
        record[meta_key] = meta
        record[key] = record["phase_pred"] if choice == "phase" else record["lag_pred"]


def selector_choice_summary(records, metric):
    choice_key = f"selector_{metric}_choice"
    choices = [r.get(choice_key, "lag") for r in records]
    phase_chosen = [r for r in records if r.get(choice_key) == "phase"]
    return {
        "n": int(len(records)),
        "phase_choice_rate": float(np.mean([c == "phase" for c in choices])) if choices else None,
        "phase_choice_n": int(len(phase_chosen)),
        "phase_choice_subset": subset_summary(phase_chosen),
    }


def mean_subset(summaries, key):
    vals = [s[key] for s in summaries if s.get(key) is not None]
    return float(np.mean(vals)) if vals else None


def aggregate_subset(horizon_summaries, horizons):
    selected = [horizon_summaries[str(h)] for h in horizons]
    keys = selected[0].keys()
    out = {}
    for key in keys:
        if key == "n":
            out[key] = int(sum(s[key] for s in selected))
        else:
            out[key] = mean_subset(selected, key)
    return out


def run():
    started = time.time()
    frame = load_enso_frame()
    dates = list(frame.index)
    series = zscore_columns(frame)
    nino_raw = series["NINO"]["raw"]
    n = len(frame)
    max_h = max(HORIZONS)
    min_anchor = max(4 * max(RUNG_KS), int(4 * BASE ** max(RUNG_KS)), 48)
    start_idx = int(np.searchsorted(np.asarray(dates, dtype="datetime64[ns]"), np.datetime64(f"{START_YEAR}-01-01"))) + 1
    test_start = max(start_idx, min_anchor + MIN_FLOW_TRAIN + max_h + 1)
    all_anchors = list(range(min_anchor, n + 1))

    print("ARA phase trust-gate diagnostic")
    print("=" * 96)
    print(f"sample: {dates[0].date()} -> {dates[-1].date()} n={n}")
    print(f"test origins start: {dates[test_start - 1].date()} stride={ORIGIN_STRIDE}")
    print("diagnostic: lag amplitude prior vs ARA phase route/timing channel")
    print("strict guards: base s+h<t; selector only uses records with target<t")
    print()

    compact_cache = {}
    phase_cache = {}
    t0 = time.time()
    for i, anchor in enumerate(all_anchors, start=1):
        compact = compact_state_features(build_snapshot(series, anchor))
        compact_cache[anchor] = compact
        phase_cache[anchor] = {key: finite(compact.get(key, 0.0)) for key in PHASE_KEYS}
        if i % 100 == 0:
            print(f"  cached states {i:4d}/{len(all_anchors)} in {time.time() - t0:.1f}s", flush=True)
    print(f"  cached states {len(all_anchors):4d}/{len(all_anchors)} in {time.time() - t0:.1f}s")
    print()

    clean_inputs = {anchor: phase_clean_input(phase_cache, anchor) for anchor in all_anchors}
    velocity_inputs = {anchor: phase_velocity_input(compact_cache, phase_cache, anchor) for anchor in all_anchors}

    records_by_h = {}
    points_by_model = {
        "lag_ridge": {},
        "ara_phase_regime_velocity": {},
        "selector_direction": {},
        "selector_mae": {},
    }

    for h in HORIZONS:
        records = []
        origins = list(range(test_start, n - h + 1, ORIGIN_STRIDE))
        for origin in origins:
            target_anchor = origin + h
            if target_anchor > n:
                continue
            train_transition = [s for s in all_anchors if s + h < origin]
            decoder_anchors = [a for a in all_anchors if a < origin]
            if len(train_transition) < MIN_FLOW_TRAIN or len(decoder_anchors) < MIN_FLOW_TRAIN:
                continue

            components = predict_components_for_origin(
                origin,
                h,
                train_transition,
                decoder_anchors,
                compact_cache,
                phase_cache,
                clean_inputs,
                velocity_inputs,
                series,
                nino_raw,
            )
            if components is None:
                continue

            actual = float(nino_raw[target_anchor - 1])
            persistence = float(components["persistence"])
            lag_pred = float(components["lag_pred"])
            phase_pred = float(components["regime_velocity_phase_pred"])
            records.append(
                {
                    "horizon": int(h),
                    "origin_anchor": int(origin),
                    "target_anchor": int(target_anchor),
                    "origin_date": dates[origin - 1].strftime("%Y-%m-%d"),
                    "target_date": dates[target_anchor - 1].strftime("%Y-%m-%d"),
                    "persistence": persistence,
                    "actual": actual,
                    "lag_pred": lag_pred,
                    "phase_pred": phase_pred,
                    "lag_delta": lag_pred - persistence,
                    "phase_delta": phase_pred - persistence,
                    "actual_delta": actual - persistence,
                    "bucket": None,
                }
            )

        for record in records:
            record["bucket"] = trust_bucket(record)
        add_selector_predictions(records, "direction")
        add_selector_predictions(records, "mae")

        records_by_h[str(h)] = records
        points_by_model["lag_ridge"][str(h)] = points_from_records(records, "lag_pred")
        points_by_model["ara_phase_regime_velocity"][str(h)] = points_from_records(records, "phase_pred")
        points_by_model["selector_direction"][str(h)] = points_from_records(records, "selector_direction_pred")
        points_by_model["selector_mae"][str(h)] = points_from_records(records, "selector_mae_pred")

        print(f"h={h:>2} months")
        for model in points_by_model:
            print(f"  {model:30s} {format_score(extended_score(points_by_model[model][str(h)]))}")
        disagree = [r for r in records if lag_phase_disagree(r)]
        transition = [r for r in records if is_transition(r)]
        print(
            "  disagreement:"
            f" n={len(disagree)} lag_turn={subset_summary(disagree)['lag_turn_accuracy']:.3f}"
            f" phase_turn={subset_summary(disagree)['phase_turn_accuracy']:.3f}"
            f" lag_mae={subset_summary(disagree)['lag_mae']:.3f}"
            f" phase_mae={subset_summary(disagree)['phase_mae']:.3f}"
        )
        print(
            "  transitions:"
            f" n={len(transition)} lag_turn={subset_summary(transition)['lag_turn_accuracy']:.3f}"
            f" phase_turn={subset_summary(transition)['phase_turn_accuracy']:.3f}"
            f" lag_mae={subset_summary(transition)['lag_mae']:.3f}"
            f" phase_mae={subset_summary(transition)['phase_mae']:.3f}"
        )
        print()

    scores = {
        model: {h: extended_score(points_by_model[model][h]) for h in points_by_model[model]}
        for model in points_by_model
    }
    subset_summaries = {}
    warning_summaries = {}
    selector_summaries = {}
    for h, records in records_by_h.items():
        agree = [r for r in records if lag_phase_agree(r)]
        disagree = [r for r in records if lag_phase_disagree(r)]
        transition = [r for r in records if is_transition(r)]
        disagree_transition = [r for r in records if lag_phase_disagree(r) and is_transition(r)]
        subset_summaries[h] = {
            "all": subset_summary(records),
            "agree": subset_summary(agree),
            "disagree": subset_summary(disagree),
            "transition": subset_summary(transition),
            "disagree_transition": subset_summary(disagree_transition),
        }
        warning_summaries[h] = warning_summary(records)
        selector_summaries[h] = {
            "direction": selector_choice_summary(records, "direction"),
            "mae": selector_choice_summary(records, "mae"),
        }

    focus = ["6", "12", "24"]
    focus_summary = {
        subset: aggregate_subset({h: subset_summaries[h][subset] for h in focus}, [6, 12, 24])
        for subset in ["all", "agree", "disagree", "transition", "disagree_transition"]
    }
    focus_scores = {
        model: {
            key: float(np.mean([scores[model][h][key] for h in focus]))
            for key in ["mae", "corr", "turn_accuracy", "enso_class_accuracy", "transition_mae"]
            if all(scores[model][h].get(key) is not None for h in focus)
        }
        for model in points_by_model
    }

    slim_records = {
        h: [
            {
                "origin": r["origin_date"],
                "target": r["target_date"],
                "persistence": rounded(r["persistence"]),
                "actual": rounded(r["actual"]),
                "lag_pred": rounded(r["lag_pred"]),
                "phase_pred": rounded(r["phase_pred"]),
                "lag_delta": rounded(r["lag_delta"]),
                "phase_delta": rounded(r["phase_delta"]),
                "actual_delta": rounded(r["actual_delta"]),
                "bucket": r["bucket"],
                "lag_correct": lag_correct(r),
                "phase_correct": phase_correct(r),
                "transition": is_transition(r),
                "selector_direction_choice": r.get("selector_direction_choice"),
                "selector_mae_choice": r.get("selector_mae_choice"),
            }
            for r in records[:12]
        ]
        for h, records in records_by_h.items()
    }

    out = {
        "date": "2026-05-25",
        "method": "strict-causal ARA phase trust-gate diagnostic",
        "leakage_guard": [
            "Base lag and phase predictions use strict-causal training pairs s+h<t.",
            "The trust selector for origin t only uses previous records whose target_anchor < t.",
            "No future actual values are used for current trust selection.",
        ],
        "system": "ENSO",
        "target": "NINO3.4 anomaly",
        "base": BASE,
        "home_period_months": HOME_PERIOD,
        "horizons_months": HORIZONS,
        "origin_stride_months": ORIGIN_STRIDE,
        "min_meta_bucket": MIN_META_BUCKET,
        "min_meta_fallback": MIN_META_FALLBACK,
        "sample": {
            "start": dates[0].strftime("%Y-%m-%d"),
            "end": dates[-1].strftime("%Y-%m-%d"),
            "n": int(n),
            "test_start_origin": dates[test_start - 1].strftime("%Y-%m-%d"),
        },
        "models": {
            "lag_ridge": "Native-unit lag/slope ridge amplitude prior.",
            "ara_phase_regime_velocity": "Regime+velocity ARA phase-flow decoded to native units.",
            "selector_direction": "Causal selector: use phase only when past completed same-risk bucket says phase has better turn accuracy and tolerable MAE.",
            "selector_mae": "Causal selector: use phase only when past completed same-risk bucket says phase has lower MAE.",
        },
        "scores": clean_for_json(scores),
        "focus_6_12_24_scores": clean_for_json(focus_scores),
        "subset_summaries": clean_for_json(subset_summaries),
        "focus_6_12_24_subset_summary": clean_for_json(focus_summary),
        "warning_summaries": clean_for_json(warning_summaries),
        "selector_summaries": clean_for_json(selector_summaries),
        "example_records": clean_for_json(slim_records),
        "elapsed_seconds": rounded(time.time() - started, 3),
    }

    OUT_JSON.write_text(json.dumps(clean_for_json(out), indent=2), encoding="utf-8")
    OUT_JS.write_text(
        "window.ARA_PHASE_TRUST_GATE_DIAGNOSTIC = " + json.dumps(clean_for_json(out), allow_nan=False) + ";\n",
        encoding="utf-8",
    )

    print("Focus 6/12/24 scores:")
    for model, score in focus_scores.items():
        print(
            f"  {model:30s}"
            f" MAE={score.get('mae', float('nan')):.3f}"
            f" corr={score.get('corr', float('nan')):+.3f}"
            f" turn={score.get('turn_accuracy', float('nan')):.3f}"
            f" transition_mae={score.get('transition_mae', float('nan')):.3f}"
        )
    print("Focus disagreement summary:")
    d = focus_summary["disagree"]
    print(
        f"  n={d['n']} lag_turn={d['lag_turn_accuracy']:.3f}"
        f" phase_turn={d['phase_turn_accuracy']:.3f}"
        f" lag_mae={d['lag_mae']:.3f} phase_mae={d['phase_mae']:.3f}"
        f" phase_only_correct={d['phase_only_correct_rate']:.3f}"
        f" lag_only_correct={d['lag_only_correct_rate']:.3f}"
    )
    print(f"Saved -> {OUT_JSON}")
    print(f"Saved -> {OUT_JS}")


if __name__ == "__main__":
    run()
